"""
🛠️ Utils Package

Utility modules.
"""

from .formatters import (
    format_date,
    format_datetime_short,
    format_file_size,
    format_list,
    format_order_number,
    format_percentage,
    format_phone,
    format_price,
    format_quantity,
    format_rating,
    format_time_ago,
    truncate_text,
)
from .helpers import (
    calculate_discount_percent,
    chunks,
    clamp,
    flatten,
    generate_order_number,
    generate_short_id,
    generate_uuid,
    get_pagination_info,
    mask_email,
    mask_phone,
    merge_dicts,
    remove_none,
    retry,
    run_with_timeout,
    safe_get,
    unique,
)
from .security import (
    DataEncryption,
    JWTHandler,
    PasswordHasher,
    create_signature,
    generate_otp,
    generate_token,
    hash_string,
    jwt_handler,
    password_hasher,
    verify_signature,
)
from .validators import (
    ProductCreateSchema,
    UserUpdateSchema,
    OrderCreateSchema,
    generate_slug,
    sanitize_html,
    sanitize_text,
    validate_email,
    validate_phone,
    validate_price,
    validate_quantity,
    validate_username,
)

__all__ = [
    # Formatters
    "format_price",
    "format_phone",
    "format_date",
    "format_datetime_short",
    "format_time_ago",
    "format_quantity",
    "format_rating",
    "format_order_number",
    "format_file_size",
    "format_percentage",
    "format_list",
    "truncate_text",
    # Helpers
    "generate_uuid",
    "generate_short_id",
    "generate_order_number",
    "chunks",
    "flatten",
    "unique",
    "safe_get",
    "merge_dicts",
    "run_with_timeout",
    "retry",
    "remove_none",
    "clamp",
    "calculate_discount_percent",
    "get_pagination_info",
    "mask_phone",
    "mask_email",
    # Security
    "PasswordHasher",
    "JWTHandler",
    "DataEncryption",
    "password_hasher",
    "jwt_handler",
    "generate_token",
    "generate_otp",
    "hash_string",
    "verify_signature",
    "create_signature",
    # Validators
    "validate_phone",
    "validate_email",
    "validate_username",
    "validate_price",
    "validate_quantity",
    "sanitize_text",
    "sanitize_html",
    "generate_slug",
    "ProductCreateSchema",
    "UserUpdateSchema",
    "OrderCreateSchema",
]
